version: "3"
services:
  api:
    container_name: dev_basic_api
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
